apiVersion: v1
kind: ConfigMap
metadata:
  name: holiday-analyzer-config
  namespace: holiday-analyzer
data:
  # Database
  POSTGRES_DB: "holidays"
  POSTGRES_USER: "postgres"
  
  # Backend
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  
  # Frontend
  VITE_API_BASE_URL: "http://backend-service:8080"
